name: Check Types and Lint
'on':
  pull_request:
    branches:
      - prod
      - dev
      - research
      - research-llm

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Check Types
        run: yarn type-check
      - name: Lint
        run: yarn lint